# Server Port
server.port=8080

# H2 Database configuration (File-based database so data is saved to a file locally)
spring.datasource.url=jdbc:h2:file:./data/baladb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate Schema generation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console to view database in browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Serve frontend directly from absolute path
spring.web.resources.static-locations=file:D:/project for bala/
